theme: jekyll-theme-minimal
title: Koala Time
description: Welcome to Koala Time! (This site is a stub for future work.)
google_analytics: UA-177940998-1
logo: images/koala-time-logo.png
logo_alt: Koala Time Logo
plugins:
  - jekyll-seo-tag
  - jekyll-menus
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-github-metadata

relative_links:
  enabled:     true
  collections: false

### Build settings ###
github:
  repository_url: https://github.com/Koala-Time/static-site
  is_project_page: true
repository: Koala-Time/static-site
baseurl: ""

# SEO Stuff
url: https://koalatime.app
twitter:
  username: koalatimeapp
  card: summary
